# GCP IAM Janitor - Docker Compose using GitHub Container Registry Images
# This configuration uses pre-built images from GitHub Container Registry

services:
  # Main service - dynamically configured based on APP_VERSION
  gcp-iam-janitor:
    image: ghcr.io/erasmus74/gcp-iam-janitor:main-${APP_VERSION:-advanced}
    container_name: gcp-iam-janitor-${APP_VERSION:-advanced}
    ports:
      - "8501:8501"
    environment:
      - APP_VERSION=${APP_VERSION:-advanced}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - GCP_PROJECT_ID=${GCP_PROJECT_ID:-your-gcp-project-id}
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/credentials/application_default_credentials.json
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONUNBUFFERED=1
    volumes:
      - ~/.config/gcloud:/gcp/credentials:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - "project=gcp-iam-janitor"
      - "environment=production"
      - "version=${APP_VERSION:-advanced}"

