# GCP IAM Janitor - Docker Compose using GitHub Container Registry Images
# This configuration uses pre-built images from GitHub Container Registry

services:
  # Default service (advanced version)
  gcp-iam-janitor:
    image: ghcr.io/erasmus74/gcp-iam-janitor:main-advanced
    container_name: gcp-iam-janitor
    ports:
      - "8501:8501"
    environment:
      - APP_VERSION=advanced
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - GCP_PROJECT_ID=${GCP_PROJECT_ID:-your-gcp-project-id}
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/credentials/application_default_credentials.json
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONUNBUFFERED=1
    volumes:
      - ~/.config/gcloud:/gcp/credentials:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - "project=gcp-iam-janitor"
      - "environment=production"
      - "version=advanced"

  # Simple version
  gcp-iam-janitor-simple:
    profiles: ["simple"]
    image: ghcr.io/erasmus74/gcp-iam-janitor:main-simple
    container_name: gcp-iam-janitor-simple
    ports:
      - "8501:8501"
    environment:
      - APP_VERSION=simple
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - GCP_PROJECT_ID=${GCP_PROJECT_ID:-your-gcp-project-id}
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/credentials/application_default_credentials.json
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONUNBUFFERED=1
    volumes:
      - ~/.config/gcloud:/gcp/credentials:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - "project=gcp-iam-janitor"
      - "environment=production"
      - "version=simple"

  # Enhanced version
  gcp-iam-janitor-enhanced:
    profiles: ["enhanced"]
    image: ghcr.io/erasmus74/gcp-iam-janitor:main-enhanced
    container_name: gcp-iam-janitor-enhanced
    ports:
      - "8501:8501"
    environment:
      - APP_VERSION=enhanced
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - GCP_PROJECT_ID=${GCP_PROJECT_ID:-your-gcp-project-id}
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/credentials/application_default_credentials.json
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONUNBUFFERED=1
    volumes:
      - ~/.config/gcloud:/gcp/credentials:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - "project=gcp-iam-janitor"
      - "environment=production"
      - "version=enhanced"

  # Consolidation version
  gcp-iam-janitor-consolidation:
    profiles: ["consolidation"]
    image: ghcr.io/erasmus74/gcp-iam-janitor:main-consolidation
    container_name: gcp-iam-janitor-consolidation
    ports:
      - "8501:8501"
    environment:
      - APP_VERSION=consolidation
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - GCP_PROJECT_ID=${GCP_PROJECT_ID:-your-gcp-project-id}
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/credentials/application_default_credentials.json
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONUNBUFFERED=1
    volumes:
      - ~/.config/gcloud:/gcp/credentials:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - "project=gcp-iam-janitor"
      - "environment=production"
      - "version=consolidation"

networks:
  default:
    name: gcp-iam-janitor-network
    driver: bridge

volumes:
  gcp_credentials:
    driver: local
    name: gcp-iam-janitor-credentials